apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadbdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path-save
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadbdata
        - name: initsql
          configMap:
            name: initdb
      containers:
      - name: mariadb
        image: mariadb:11
        volumeMounts:
          - name: initsql
            mountPath: /docker-entrypoint-initdb.d/init.sql
            subPath: init.sql
            readOnly: true
          - name: data
            mountPath: /var/lib/mysql
        env:
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: voucher-config
              key: MYSQL_DATABASE
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: MYSQL_ROOT_PASSWORD
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: MYSQL_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: MYSQL_PASSWORD
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3306
