services:
  voucher-web:
    build:
      context: https://github.com/yogi7777/voucher.git#main
      dockerfile: docker/Dockerfile
      no_cache: true
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - voucher-network
    restart: always

  db:
    build:
      context: https://github.com/yogi7777/voucher.git#main
      dockerfile: database/Dockerfile
      no_cache: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - voucher-network
    restart: always


networks:
  voucher-network:
    driver: bridge

volumes:
  app_data:
  db_data:
