version: '3.8'

services:
  voucher-web:
    build:
      context: https://github.com/yogi7777/voucher.git#main
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=voucher
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - voucher-network
    restart: always

  db:
    build:
      context: https://github.com/yogi7777/voucher.git#main
      dockerfile: database/Dockerfile
    environment:
      - MYSQL_DATABASE=voucher
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - voucher-network
    restart: always

networks:
  voucher-network:
    driver: bridge

volumes:
  app_data:
  db_data: